feat(entrypoint): select default entrypoint
moneytrackio/tezos_client pull request #43
Opened 2020-09-23 12:15 UTC by SebastienLAURET

add select entrypoint methode

2020-09-23 13:01 UTC, elkesrio commented on lib/tezos_client.rb
> +  def select_entrypoint(contract_address:, entrypoint:)
tu peux tester cette méthode ?

2020-09-23 13:23 UTC, Pierre-Michard commented on lib/tezos_client.rb
>    def call_contract(dry_run: false, entrypoint:, params:, params_type:, **args)
faudrait tester le cas ou l'on appelle un contrat qui n'a qu'un entrypoint et qu'on appellerait avec le nom de cet entrypoint.

2020-09-25 10:05 UTC, Pierre-Michard requested changes

2020-09-25 10:05 UTC, Pierre-Michard commented on spec/tezos_client/rpc_interface/contracts_spec.rb
> +    pp "HERE"
faudrait virer ces puts qui trainent

2020-09-25 10:13 UTC, elkesrio approved these changes

2020-09-25 12:32 UTC, merged